"""create users and tasks tables

Revision ID: 001_initial
Revises:
Create Date: 2024-01-01 00:00:00.000000

=============================================================================
EXAMPLE MIGRATION — generated by Alembic autogenerate.
In practice you'd run:
    alembic revision --autogenerate -m "create users and tasks tables"
and Alembic generates this file for you.

DRF EQUIVALENT:
    Django auto-generates this from models.py when you run:
    python manage.py makemigrations

Key difference: Alembic gives you EXPLICIT downgrade() methods.
Django's --fake approach or squashing is less clean for rollbacks.
=============================================================================
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers — Alembic uses these to track migration order
revision: str = "001_initial"
down_revision: Union[str, None] = None  # This is the first migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply the migration: create users and tasks tables.

    DRF EQUIVALENT: The auto-generated operations inside a Django Migration class:
        operations = [
            migrations.CreateModel(name='User', fields=[...]),
            migrations.CreateModel(name='Task', fields=[...]),
        ]

    Alembic gives you raw DDL control — you can add indexes, constraints,
    and defaults that Django migrations sometimes struggle with.
    """

    # ------------------------------------------------------------------
    # Create users table
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Indexes for fast lookups
    op.create_index("ix_users_id", "users", ["id"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # ------------------------------------------------------------------
    # Create tasks table
    # ------------------------------------------------------------------
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            server_default="todo",
        ),
        sa.Column(
            "priority",
            sa.String(length=50),
            nullable=False,
            server_default="medium",
        ),
        sa.Column("is_completed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        # Foreign key: owner_id REFERENCES users(id) ON DELETE CASCADE
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Indexes
    op.create_index("ix_tasks_id", "tasks", ["id"], unique=False)
    op.create_index("ix_tasks_title", "tasks", ["title"], unique=False)
    op.create_index("ix_tasks_status", "tasks", ["status"], unique=False)
    op.create_index("ix_tasks_priority", "tasks", ["priority"], unique=False)
    op.create_index("ix_tasks_owner_id", "tasks", ["owner_id"], unique=False)


def downgrade() -> None:
    """
    Rollback this migration: drop tasks and users tables.

    DRF EQUIVALENT: Django migrations don't always generate clean downgrade
    code. Alembic's downgrade() is explicit and reliable.

    Run with: alembic downgrade -1
    """
    # Drop tables in reverse dependency order (tasks references users)
    op.drop_index("ix_tasks_owner_id", table_name="tasks")
    op.drop_index("ix_tasks_priority", table_name="tasks")
    op.drop_index("ix_tasks_status", table_name="tasks")
    op.drop_index("ix_tasks_title", table_name="tasks")
    op.drop_index("ix_tasks_id", table_name="tasks")
    op.drop_table("tasks")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
